### PR TITLE
[System tests] Extracting contract deployment for system tests

### PR DESCRIPTION
**Pull request by dimpar**
Currently we have duplicate code which deploys the same contracts for the system tests. To make it cleaner, this change extracts common code for contract deployments and introduces contract constants for tests.
Existing tests are refactored according to the above changes. Future system tests should reuse proposed functionality.

These changes are refactoring only, no new system tests were added.

### CODE REVIEW

**Review by lukasz-zimnoch — COMMENTED** [review]
Looks good but let's hold off with merging until all system tests PRs land on main.

**Comment by dimpar** [comment]
If we wait on all other system tests PRs to land on main, then we will have even more files in conflict to refactor in the future. Some of the comments in the pending PRs can be resolved automatically with this guy. Plus some new tests might be added parallel to this PR. I'd rather actually merge this guy first to setup the structure for all other system tests to rely on.

**Comment by pdyraga** [comment]
I'd also love to merge this one before other system tests land. We will have some conflicts but the review process should be much easier.

**Comment by dimpar** [comment]
> I'd also love to merge this one before other system tests land. We will have some conflicts but the review process should be much easier.

**Review by lukasz-zimnoch — APPROVED** [review]

**Comment by pdyraga** [comment]
What about `test/system/deposit-liquidated-externally.test.js`?

**Comment by dimpar** [comment]
> What about `test/system/deposit-liquidated-externally.test.js`?

Slipped from the radar.. pls see https://github.com/keep-network/coverage-pools/pull/113

**Pull request merged**
