### PR TITLE
Prepare NPM package structure for package publication

### PR DESCRIPTION
**Pull request by nkuba**
This PR implements what was previously described in https://github.com/keep-network/coverage-pools/issues/159.

## Structure

The package will have the following structure:
```
artifacts/               # copy of deployments/<network>/
build/contracts/         # build artifacts
contracts/               # source code
export.json              # single-file deployment export
```

- `artifacts/` - is a directory containing deployed contracts artifacts for the network the package is being created. It is assumed that a package is published for each supported network separately as per the [RFC-18](https://github.com/keep-network/keep-core/blob/main/docs/rfc/rfc-18-release-management.adoc), so we don't need to create separate directories per network.
- `build/contracts/` - is a directory containing compiled contracts artifacts in the Hardhat format.
- `contracts/` - is a directory containing contracts source code.
- `export.json` - lightweight deployment data in a single file.

## Scripts

There was a script created to prepare the `artifacts/` directory. The script can be executed with:
```
./scripts/prepare-artifacts.sh --network <network>
```

In `package.json` we defined a `prepublishOnly` entry that will execute before the package is packed and published if `npm publish` command is run. It expects the network option to be provided like in the following example:
```
npm publish --dry-run --network=ropsten
```
or
```
npm_config_network=development yarn publish
```

The command can be also executed separately with:
```
npm run prepublishOnly --network=ropsten
```
or
```
npm_config_network=development yarn prepublishOnly
```

Closes: https://github.com/keep-network/coverage-pools/issues/159

### CODE REVIEW

**Comment by nkuba** [comment]
@michalinacienciala We can use this feature in CI to prepare the package for publication after migration.

**Comment by michalinacienciala** [comment]
> @michalinacienciala We can use this feature in CI to prepare the package for publication after contracts migration.
Applied in https://github.com/keep-network/coverage-pools/pull/155.

**Comment by michalinacienciala** [comment]
It may not be strictly related to changes in this PR, but maybe we could update [this line in README.adoc](https://github.com/keep-network/coverage-pools/blame/npm-package-structure/README.adoc#L90) to "Compiled contracts will land in the `build/contracts` directory"?

**Review by michalinacienciala — COMMENTED** [review]
I've tested the script locally and haven't found any issues. The only comment I had was not strictly related to changes in this PR. Leaving for @r-czajkowski to review.

**Review by r-czajkowski — COMMENTED** [review]
I think we should run `prepare-artifacts.sh` script instead of creating a symlink in the [`install.sh`](https://github.com/keep-network/coverage-pools/blob/main/scripts/install.sh#L69). Ofc non-blocking comment and we can address it in a separate PR.

Looking good on my side! 👍

**Comment by nkuba** [comment]
Nice findings @michalinacienciala and @r-czajkowski! I updated the code, ready for a final shot!

**Review by r-czajkowski — APPROVED** [review]
LGTM! 👍

**Review by michalinacienciala — APPROVED** [review]

**Pull request merged**
